### ISSUE TITLE
결빙 예측 신뢰성 강화

### ISSUE THREAD

**Issue by suhwan-cheon** [GEOor/GEOorWeb#20]
![image](https://user-images.githubusercontent.com/52690419/147304707-cecff843-7afd-4797-8dc4-15e5ef68f3da.png)

회사 요구사항은 만족하였으나, 발표 시 다음과 같은 문제가 우려됨

[현재 문제점]
- 오직 음영기복도 하나만으로 결빙 예측을 하고자 함
- 상식적으로 평균 기온이 높은 여름에는 웬만하면 도로에 결빙이 일어나진 않음
- 눈, 비가 오지 않는 한 웬만하면 결빙이 일어나지 않음

[해결 방법]
- 기온, 강우 강수, 논문 조사때 확인한 vms 자료들을 이용해 알고리즘을 하나 더 만들거나, 각기 다르게 만들고 가중치를 나눠주는 작업이 필요해 보임
- 가능할지는 모르겠으나 교량 또는 주변에 강이 있는 경우도 고려하면 더 좋은 결과가 나올 것으로 기대됨

**Comment by kimtaehyun98** [comment]
문제점 보단 개선 사항으로 발표하면 좋을듯!
